#!/bin/bash
source ~/.bash_profile

DTSTR=`date "+%m%d%Y"`
TMP=/tmp

#mkdir -p $TMP/$DTSTR

echo "Backing up database..."
rm -f $TMP/game_recommender.sql $TMP/game_recommender.sql.gz
mysqldump -h localhost -u $DB_USER --password=$DB_PASSWORD \
	--databases game_recommender > $TMP/game_recommender.sql
gzip $TMP/game_recommender.sql

echo "Backing up localhost database..."
rm -f $TMP/steam_data.sql $TMP/steam_data.sql.gz
mysqldump -h localhost -u $DB_USER --password=$DB_PASSWORD \
	--databases steam_data > $TMP/steam_data.sql
gzip $TMP/steam_data.sql

HOME=/home/wkerr/Dropbox
DEST=$HOME/steamrecommender/backup/$DTSTR
mkdir -p $DEST

mv $TMP/game_recommender.sql.gz $DEST/
mv $TMP/steam_data.sql.gz $DEST/

cp /data/steam/sample-ratings-file.gz $HOME/steamrecommender/
cp /data/steam/sample-training-data.gz $HOME/steamrecommender/

