#!/bin/bash
set -e
source ~/.bash_profile

cd /steamrecommender
echo $PATH
export PATH=$PATH:/usr/local/bin

java -cp /steamrecommender/recommender.jar com.wesleykerr.steam.etl.UpdateSteamDataset -r daily

