#!/bin/bash
source ~/.bash_profile

echo $PATH
export PATH=$PATH:/usr/local/bin

cd /data/steam/
dtstr=`date --date='last Monday' "+%m%d%Y"`

mv player-updates player-updates-$dtstr
gzip player-updates-$dtstr

hadoop fs -copyFromLocal player-updates-$dtstr.gz /steam/raw/$dtstr/player-updates.gz


