#!/bin/bash
set -e
source ~/.bash_profile

DTSTR_START=`date "+%Y-%m-%d" --date="3 days ago"`
DTSTR_END=`date "+%Y-%m-%d"`
DATA=/data/steam
TRAIN=$DATA/sample-training-data
rm -f ${TRAIN}.gz

echo "...extract data from MySQL"
mysql -u $DB_USER --password=$DB_PASSWORD -e "
  select steamid, content
  from steam_data.players_sample
  where private = 0
  and date(last_updated) >= '$DTSTR_START'
  and date(last_updated) < '$DTSTR_END'
  into outfile '$TRAIN'
  fields terminated by '\t'
"
gzip $TRAIN

export PATH=$PATH:/usr/local/bin
cd /usr/local/game-recommender

echo "...prepare training data"
java -cp recommender.jar com.wesleykerr.recommender.TrainingData \
	-i $TRAIN.gz -o $DATA/sample-ratings-file.gz

echo "...run collaborative filter"
java -cp ml.jar com.wesleykerr.ranking.CollaborativeFilter \
	-i $DATA/sample-ratings-file.gz -o $DATA/sampling-model.csv

echo "...deploy model"
java -cp recommender.jar com.wesleykerr.recommender.DeployModel \
	-i $DATA/sampling-model.csv -m 1

echo "...update steam"
java -cp recommender.jar com.wesleykerr.steam.etl.UpdateSteamDataset \
        -r weekly -i $TRAIN.gz -o /data/steam/playtime

java -cp recommender.jar com.wesleykerr.steam.tools.GameRecommendations

# copy over the training data in order to access it
# from work without spinning up a database in order to get it.
sshpass -p $RSYNC_PASSWORD \
  rsync -e ssh -av ${TRAIN}.gz b418667@hanjin.dreamhost.com:steam

