#!/bin/bash
set -e
source /steamrecommender/config/site_overrides

DTSTR_START=`date "+%Y-%m-%d" --date="30 days ago"`
DTSTR_END=`date "+%Y-%m-%d"`
DATA=/data
TRAIN=$DATA/sample-training-data
rm -f ${TRAIN}.gz

echo "...extract data from MySQL"
mysql --login-path=local -e "
  select steamid, content
  from steam_data.players_sample
  where private = 0
  and date(last_updated) >= '$DTSTR_START'
  and date(last_updated) < '$DTSTR_END'
  into outfile '$TRAIN'
  fields terminated by '\t'
"
gzip $TRAIN

cd /steamrecommender
export PATH=$PATH:/usr/local/bin

echo "...prepare training data"
java -Xmx1024m -cp /steamrecommender/recommender.jar com.wesleykerr.recommender.TrainingData \
	-i $TRAIN.gz -o $DATA/sample-ratings-file.gz

echo "...run collaborative filter"
java -Xmx1024m -cp /steamrecommender/ml.jar com.wesleykerr.ranking.CollaborativeFilter \
	-i $DATA/sample-ratings-file.gz -o $DATA/sampling-model.csv

echo "...deploy model"
java -cp /steamrecommender/recommender.jar com.wesleykerr.recommender.DeployModel \
	-i $DATA/sampling-model.csv -m 1

echo "...update steam"
java -cp /steamrecommender/recommender.jar com.wesleykerr.steam.etl.UpdateSteamDataset \
        -r weekly -i $TRAIN.gz -o /data/steam/playtime

java -cp /steamrecommender/recommender.jar com.wesleykerr.steam.tools.GameRecommendations


