#!/bin/bash

echo $PATH
export PATH=$PATH:/usr/local/bin
cd /usr/local/game-recommender
echo `pwd`
DATA=/Users/wkerr/data/steam

cp $DATA/player-updates /tmp/player-updates
rm -f /tmp/player-updates.gz
gzip /tmp/player-updates

hadoop fs -rmr /steam/raw/current/player-updates.gz
hadoop fs -copyFromLocal /tmp/player-updates.gz /steam/raw/current/player-updates.gz
hadoop jar recommender.jar com.wesleykerr.recommender.RecentData /steam/raw/* /steam/data

rm -f $DATA/training-data.gz
hadoop fs -copyToLocal /steam/data/part-r-00000.gz $DATA/training-data.gz

